[project]
name = "twitter-forward-to-telegram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.51.0",
    "fastapi",
    "httpx",
    "openai>=1.84.0",
    "pydantic",
    "uvicorn",
]
